stages:
    - deploy

deploy-dev:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - cat $ENV_FILE > .env
        - rsync -ahrz --delete-after -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $CI_PROJECT_DIR/ $CI_DEV_USER@$CI_DEV_IP:$CI_DEV_PATH
        - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $CI_DEV_USER@$CI_DEV_IP "cd $SOURCE_PATH && bash deploy-agent.sh"

    tags:
        - agent-service
    only:
        - develop

deploy-prod:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - cat $PRD_ENV_FILE > .env
        - rsync -ahrz --delete-after -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $CI_PROJECT_DIR/ $CI_PRD_USER@$CI_PRD_IP:$CI_PRD_PATH
        - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $CI_PRD_USER@$CI_PRD_IP "cd $SOURCE_PATH && bash agent.sh"

    tags:
        - prod
    only:
        - main
