stages:
    - build
    - deploy

build:
    stage: build
    script:
        - cat $ENV_FILE > .env
    tags:
        - agent-service
    only:
        - develop

deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - rsync -ahrz --delete-after -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $CI_PROJECT_DIR/ $CI_DEV_USER@$CI_DEV_IP:$CI_DEV_PATH
        - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $CI_DEV_USER@$CI_DEV_IP "cd $CI_DEV_PATH && pip install -r stable-requirements.txt && python3 manage.py makemigrations && python3 manage.py migrate"
        - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $CI_DEV_USER@$CI_DEV_IP "cd $CI_DEV_PATH && kill -9 $(ps -ef | grep "/usr/bin/python3 manage.py run_grpc_server" | grep -v grep | awk '{print $2}') || true"
        - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $CI_DEV_USER@$CI_DEV_IP "cd $SOURCE_PATH && bash deploy-agent.sh"

    tags:
        - agent-service
    only:
        - develop
